---
  - hosts: all
    

    tasks:

      - name: Actualizar paquetes
        apt:
         update_cache: yes
        become: true

      - name: Ruby
        apt: pkg=ruby state=latest
        become: true

      
      - name: gcc
        apt: pkg=gcc state=latest
        become: true

      - name: make
        apt: pkg=make state=latest
        become: true
      
      - name: ruby-dev
        apt: pkg=ruby-dev state=latest
        become: true

      - name: mongodb
        apt: pkg=mongodb state=latest
        become: true

      - name: Bundler
        apt: pkg=bundler state=latest
        become: true

      - name: Clonar el repositorio
        git: repo=https://github.com/juanmaLC/ProyectoIV.git dest=ProyectoIV/  

      
    
      - gem: 
         name: sinatra
         state: latest

      - gem: 
         name: bundler
         state: latest
      

      - gem: 
         name: rspec
         state: latest

